### ISSUE TITLE
Advanced Brush System: Custom Brush Styles, Mixer Filters, and Rubber Stamps

### ISSUE THREAD

**Issue by bchou9** [GabeBai/Res-Convas#14]
## Description
Currently the canvas supports basic freehand and shape drawing. We want a rich brush/filter/stamp system inspired by classic drawing apps (Kid Pix / Tux Paint) — a set of creative brushes (wacky brushes with effects and repeat stamps), a Mixer (global image filters/effects), and a Rubber Stamp tool with an editable stamp library.

## Current workflow
- Users can draw freehand shapes and simple shapes on the canvas.
- No plug-in style brush/effects system, no global filters, and no stamp library.

## Proposed solution
Implement an extensible brush plugin system, a Mixer tool with preview and non-destructive application (undoable), and a Stamp tool with a built-in stamp library and a simple stamp editor.

## Technical requirements

**Files to create:**
- `frontend/src/components/BrushEditor/BrushPanel.jsx`
- `frontend/src/components/BrushEditor/WackyBrushPreview.jsx`
- `frontend/src/components/Mixer/MixerPanel.jsx`
- `frontend/src/components/Stamps/StampPanel.jsx`
- `frontend/src/components/Stamps/StampEditor.jsx`
- `frontend/src/hooks/useBrushEngine.js`
- `frontend/src/styles/brushes.css`

**Files to modify:**
- `Canvas.js` (integrate brush engine, new brush palette, render preview)
- `Toolbar.js` (add controls for Brushes/Mixer/Stamps)
- `drawing.js` (add support for stroke meta describing brush type / stamp placement / filter markers)
- `canvasBackendJWT.js` (if stamps or brushes should be saved/loaded to server)

**Optional backend (for persistence/catalogs):**
- `backend/routes/stamps.py` (CRUD for stamp library)
- `db.py` (add stamps collection usage)

## Skills needed
- Advanced React/JS (state, hooks, performant canvas rendering)
- 2D canvas rendering & compositing
- UX design for tool palettes
- Optional: Express/Flask + MongoDB CRUD

## Key features to implement
- Brush plugin architecture (brush id, params, preview render function)
- Several built-in fancy brushes (Wacky Brush: pattern trails, dripping effects, shape scatter brush)
- Mixer tool applying non-destructive filters (blur, hue shift, chalk, fade) with preview and undo
- Rubber Stamp tool with library (PNG/SVG stamps), scaling/rotate, editable stamps (simple crop/scale)
- Stamp import/export (zip or single image)
- Keyboard shortcuts and undo/redo integration
- Performance optimization for large canvases (tiling, batching)

## Technical challenges
- High-performance rendering for particle/trail brushes on large canvases
- Non-destructive filter application while retaining undo/redo semantics
- Handling stamp assets (storage, caching, memory)
- UI/UX complexity for many brush options without overwhelming users

## Getting started
- Fork, feature branch: `feature/advanced-brushes`
- Implement the brush engine hook + preview component
- Add the UI panels and wire them to Canvas.js
- Add a couple of sample brushes and a Mixer filter
- If persistence desired, add backend stamps route + simple CRUD
- Add tests for brush param serialization and Mixer’s non-destructive behavior

## Tests to add
- Unit: brush param → canonical serialized metadata (happy path + invalid params)
- Integration: applying a Mixer filter then undo returns original buffer
- UI: stamp import → appears in library and can be placed onto canvas
- Performance: rendering 100 small stamp placements without dropping frame budget

## Resources
- MDN Canvas API
- Example brush algorithms (scatter brush, line-following particle trails)

**Comment by kunjal2002** [comment]
I used the following : 

username : kunjal
pwd : 12345

**Comment by bchou9** [comment]
The password must be at least 6 characters, hence the 400 server side error that you are seeing. I fixed the code and now it should remind you to have a longer password.

Pull from main and try registering again. Let me know if there are any issues.

**Comment by kunjal2002** [comment]
It is giving me 500 internal error. I tried all the combinations of the password..

**Comment by kunjal2002** [comment]
I am still getting the 500 internal server error.

Username : kunj51
Password : Hack501

I tried different combinations of pwd like hack51, Hack51, hacker, hacktober but still the same error.

**Comment by chris315654** [comment]
Hi @kunjal2002 , 

Sorry for the late reply. I will be posting a more complete Readme to walk through the whole setup process. You might check and see if there is any missing step. For now, may I see the error messages in the terminal where your backend is currently running?

**Comment by bchou9** [comment]
@kunjal2002 I was not able to reproduce the 500 internal server error that you mentioned as register and login both work fine on my end.

Since you are having trouble registering, @chris315654 will assist you further in resolving the technical issues that you are facing on your end, so that you can create your own account.

**Comment by chris315654** [comment]
Got it. Do you want to meet today, tomorrow, or later this week? We can do zoom, discord, or google meet.

**Comment by chris315654** [comment]
Got it. Henry and I will be available any time after 11am tomorrow. What time will you prefer?
Here is a temporary meeting https://meet.google.com/tqr-cqwt-szg

**Comment by kunjal2002** [comment]
11 am works. 

Thank you for sharing the meet link

**Comment by kunjal2002** [comment]
https://github.com/ResilientApp/ResCanvas/pull/60

Can you review?
